channels:
- conda-forge
dependencies:
- python=3.11.0
- pip<=22.3
- pip:
  - mlflow==2.20.3
  - cloudpickle==3.1.1
  - numpy==1.24.4
  - pandas==2.2.3
  - psutil==7.0.0
  - scikit-learn==1.6.1
  - scipy==1.14.1
name: mlflow-env
